# Generated by Django 2.2 on 2021-08-27 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='titre de la question')),
                ('date_de_publication', models.DateTimeField(verbose_name='date de publication')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionuser', to=settings.AUTH_USER_MODEL, verbose_name='celui qui a pose la question')),
            ],
        ),
    ]
