# Generated by Django 3.2.6 on 2021-08-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210817_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', 'timestamp']},
        ),
    ]
